---
title: MOHD SAFWAN
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: syntax
blog_name: Segmentation Fault
tagline: Homepage
description: This is me in HTML
url: https://safwankdb.github.io
baseurl: ''
version: '4.20'
author:
  name: Mohd Safwan
  url: https://safwankdb.github.io
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
sidebar_blog_link: "/blog"
disqus:
  shortname: safwankdb
google-analytics: UA-154849191-1
